### ISSUE TITLE
Use the latest version of WebDriverManager v5.7.0

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/chromedriverfactory#57]
Chrome has been automatically upgraded to v122, which caused a problem

<img width="1552" alt="Screenshot 2024-03-10 at 08 56 08" src="https://github.com/kazurayam/chromedriverfactory/assets/4467417/58e68205-73f3-4681-b206-9ca5dbd0f2eb">

```
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 122.0.6261.112 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'KAZUAKInoMacBook-Air-2.local', ip: 'fe80:0:0:0:14a5:ce6d:929e:fcb1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.3.1', java.version: '21.0.1'
Driver info: driver.version: ChromeDriverFactoryImpl$newChromeDriver
remote stacktrace: 0   chromedriver                        0x00000001094e76b8 chromedriver + 4937400
1   chromedriver                        0x00000001094deb73 chromedriver + 4901747
2   chromedriver                        0x000000010909c616 chromedriver + 435734
3   chromedriver                        0x00000001090ced10 chromedriver + 642320
4   chromedriver                        0x00000001090ca18a chromedriver + 622986
5   chromedriver                        0x00000001090c667c chromedriver + 607868
6   chromedriver                        0x000000010910da08 chromedriver + 899592
7   chromedriver                        0x000000010910cebf chromedriver + 896703
8   chromedriver                        0x0000000109103de3 chromedriver + 859619
9   chromedriver                        0x00000001090d1d7f chromedriver + 654719
10  chromedriver                        0x00000001090d30de chromedriver + 659678
11  chromedriver                        0x00000001094a32ad chromedriver + 4657837
12  chromedriver                        0x00000001094a8130 chromedriver + 4677936
13  chromedriver                        0x00000001094aedef chromedriver + 4705775
14  chromedriver                        0x00000001094a905a chromedriver + 4681818
15  chromedriver                        0x000000010947b92c chromedriver + 4495660
16  chromedriver                        0x00000001094c6838 chromedriver + 4802616
17  chromedriver                        0x00000001094c69b7 chromedriver + 4802999
18  chromedriver                        0x00000001094d799f chromedriver + 4872607
19  libsystem_pthread.dylib             0x00007ff80fb42202 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff80fb3dbab thread_start + 15

	at java.base@21.0.1/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base@21.0.1/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base@21.0.1/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at app//org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at app//org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at app//org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base@21.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@21.0.1/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	at java.base@21.0.1/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base@21.0.1/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base@21.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base@21.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@21.0.1/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@21.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@21.0.1/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at app//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at app//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at app//com.kazurayam.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriver(ChromeDriverFactoryImpl.java:120)
	at com.kazurayam.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriver.call(Unknown Source)
	at app//org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at app//examples.LaunchChromeWithoutProfile.test_launch_browser(LaunchChromeWithoutProfile.groovy:19)
	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at app//org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at app//org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

I need to use the new version of WebDriverManager

https://github.com/bonigarcia/webdrivermanager/releases

there I found v5.7.0 was released 2 weeks ago.

**Comment by kazurayam** [comment]
done at v0.7.0
