### ISSUE TITLE
ChromeUserProfile.toString() is badly formatted

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/chromedriverfactory#61]
The following is badly formated
```
ChromeUserProfile of "onmicrosoft" is not found in :
["{\"userProfile\":\"Guest\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Guest Profile\"}","{\"userProfile\":\"Person 1\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Default\"}","{\"userProfile\":\"Person 2\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Profile 1\"}","{\"userProfile\":\"Person 2\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Profile 2\"}","{\"userProfile\":\"Person 2\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Profile 3\"}","{\"userProfile\":\"Person 2\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"Profile 4\"}","{\"userProfile\":\"Person 2\",\"userDataDir\":\"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data\",\"profileDirectoryName\":\"System Profile\"}"]
```

It should rather be

```
ChromeUserProfile of "onmicrosoft" is not found in :
[
    {"userProfile":"Guest","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Guest Profile"},
    {"userProfile":"Person 1","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Default"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 1"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 2"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 3"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 4"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"System Profile"}
]
```

**Comment by kazurayam** [comment]
Done

```
ChromeUserProfile of "onmicrosoft" is not found in :
[
    {"userProfile":"Guest","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Guest Profile"},
    {"userProfile":"Person 1","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Default"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 1"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 2"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 3"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"Profile 4"},
    {"userProfile":"Person 2","userDataDir":"C:\\Users\\hcuser\\AppData\\Local\\Google\\Chrome\\User Data","profileDirectoryName":"System Profile"}
]
```

**Comment by kazurayam** [comment]
Done at 0.7.0-SNAPSHOT

```
> Task :testClasses UP-TO-DATE
[Test worker] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 123.0.6312.58 (resolved driver for Chrome 123)
[Test worker] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/mac-x64/chromedriver-mac-x64.zip
[Test worker] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver-mac-x64.zip
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/kazuakiurayama/.cache/selenium/chromedriver/mac64/123.0.6312.58/chromedriver

com.kazurayam.webdriverfactory.WebDriverFactoryException: ChromeUserProfile of "Picasso" is not found in :
[
	{"userProfile":"Kazuaki","userDataDir":"/Users/kazuakiurayama/Library/Application Support/Google/Chrome","profileDirectoryName":"Default"},
	{"userProfile":"Person 1","userDataDir":"/Users/kazuakiurayama/Library/Application Support/Google/Chrome","profileDirectoryName":"Profile 17"},
	{"userProfile":"ゲスト","userDataDir":"/Users/kazuakiurayama/Library/Application Support/Google/Chrome","profileDirectoryName":"Guest Profile"},
	{"userProfile":"ユーザー 1","userDataDir":"/Users/kazuakiurayama/Library/Application Support/Google/Chrome","profileDirectoryName":"System Profile"}
]
	at com.kazurayam.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriver(ChromeDriverFactoryImpl.java:163)
	at com.kazurayam.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriver.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.kazurayam.webdriverfactory.chrome.ChromeDriverFactoryTest.test_if_cookie_file_is_cloned_TO_GO(ChromeDriverFactoryTest.groovy:193)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	
```

**Comment by kazurayam** [comment]
done at v0.7.0
